# Generated by Django 3.1.5 on 2021-02-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0002_auto_20210204_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('super_category__order', 'super_category__name', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Products_app.category',),
        ),
    ]
