# Generated by Django 3.1.5 on 2021-02-04 13:30

import Products_app.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0003_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to=Products_app.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('producing_country', models.CharField(choices=[(None, '------------------------------'), ('UA', 'Украина'), ('RU', 'Россия'), ('PL', 'Польша'), ('BL', 'Белорусь'), ('CN', 'Китай')], max_length=24, null=True, verbose_name='Страна производитель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('currency', models.CharField(choices=[(None, '------------------------------'), ('грн.', 'UAH'), ('долл.', 'USD'), ('ев.', 'EUR')], max_length=8, null=True, verbose_name='Валюта')),
                ('description', models.TextField(max_length=256, verbose_name='Описание')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products_app.subcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Products_app.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products_app.product', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
