# Generated by Django 3.1.5 on 2021-02-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0004_auto_20210204_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalImage',
            new_name='AdditionalImages',
        ),
    ]
