# Generated by Django 3.1.5 on 2021-02-14 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0007_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.CreateModel(
            name='CommentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('+', 'plus'), ('-', 'minus')], max_length=10, verbose_name='Последнее действие')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products_app.comment', verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проголосовавший пользователь')),
            ],
        ),
    ]
