# Generated by Django 3.1.5 on 2021-02-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0008_auto_20210214_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrating',
            name='voted',
            field=models.BooleanField(default=False, verbose_name='Уже голосовал?'),
        ),
        migrations.AlterField(
            model_name='commentrating',
            name='action',
            field=models.CharField(choices=[('+', 'plus'), ('-', 'minus')], default=None, max_length=10, verbose_name='Последнее действие'),
        ),
        migrations.AlterField(
            model_name='commentrating',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products_app.comment', verbose_name='Комментарий'),
        ),
    ]
