# Generated by Django 3.1.5 on 2021-02-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0009_auto_20210214_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentrating',
            old_name='action',
            new_name='last_action',
        ),
    ]
