# Generated by Django 3.1.5 on 2021-02-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0010_auto_20210214_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products_app.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='commentrating',
            name='last_action',
            field=models.CharField(choices=[('+', 'plus'), ('-', 'minus')], default=False, max_length=10, verbose_name='Последнее действие'),
        ),
    ]
